[package]
name = "ck"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sea-orm = { version = "0.11", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "postgres-array"] }
serde = { version = "1.0", features = ["derive"] }