[package]
name = "magnetar_webfinger"
version = "0.1.0"
edition = "2021"

[dependencies]
magnetar_core = { path = "../core", version = "0.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"